build: updating root dependencies

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -29,6 +29,16 @@ then
 fi
 
 if ! ./gradlew clean --parallel \
+      starter:assemble starter:publishToMavenLocal --stacktrace \
+      security:assemble security:publishToMavenLocal --stacktrace \
+      data-commons:assemble data-commons:publishToMavenLocal --stacktrace \
+      -Pgroup=com.github.softwareplace.springboot --refresh-dependencies -Pversion="$buildTag" --stacktrace;
+then
+  echo "Publish sub-plugins failed $buildTag"
+  exit 1
+fi
+
+if ! ./gradlew clean --parallel \
       :assemble :publishToMavenLocal --stacktrace \
       -Pgroup=com.github.softwareplace.springboot --refresh-dependencies -Pversion="$buildTag" --stacktrace;
 then
